version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.27
    container_name: nest-prisma
    restart: always
    ports:
      - "3200:4466"
    environment:
      PRISMA_CONFIG: |
        # managementApiSecret: abcdefg #prisma-deploy secret
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    image: postgres
    container_name: nest-postgres
    restart: always
    ports:
      - "3100:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: